### ISSUE TITLE
Sometimes not all of the led bulbs are activated

### ISSUE THREAD

**Issue by twister21** [iskramac/milight-v6-api#1]
Hello,

I've experienced that sometimes not all of my milight led bulbs will switch on if I use the method turnOn() although the zoneId is set to 0. So far I wasn't able to understand whether there is a specific time or sequence of actions which have to be done to get this effect. However, the official Mi-Light app works properly.

Did you collect similar experiences or is it my fault?

**Comment by iskramac** [comment]
I have noticed similar issues when I try to turn on bulbs at the same time (in different threads). That is because of limitless bridge session handling, if it is possible, synchronize invocations to bridge, and keep threshold not higher than 5 request/ sec.
